# Flight Price Prediction - Data Preprocessing

## 1. Importing Libraries

In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

## 2. Reading Data

In [2]:
df = pd.read_csv('../data/flight_price.csv')
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [3]:
df.shape

(10683, 11)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

- Dataset contains 10683 rows and 11 features
- `Route`, `Total_Stops` have missing value
- Data types of some features is not appropriate

## 3. Analysis

### Check for Duplicates

In [5]:
df.duplicated().sum()

np.int64(220)

In [6]:
df[df.duplicated(keep=False)]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
33,Jet Airways,15/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,12:35 16 Jun,22h,2 stops,In-flight meal not included,10919
49,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
73,Jet Airways,24/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 25 Jun,13h 30m,2 stops,No info,12819
81,Jet Airways,24/03/2019,Banglore,New Delhi,BLR → DEL,19:55,22:35,2h 40m,non-stop,No info,7229
87,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,04:25 07 Jun,18h 45m,2 stops,No info,13014
...,...,...,...,...,...,...,...,...,...,...,...
10594,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 28 Jun,13h 30m,2 stops,No info,12819
10616,Jet Airways,1/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 02 Jun,26h 55m,2 stops,No info,13014
10634,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 07 Jun,26h 55m,2 stops,In-flight meal not included,11733
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704

- There are 220 duplicated rows, that should be removed.

### Airline

In [7]:
df['Airline'].unique()

<StringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [8]:
(
    df['Airline'].str.replace(' Premium economy', "")
    .str.replace(' Business', "")
    .str.title()
    .unique()
)

<StringArray>
[           'Indigo',         'Air India',       'Jet Airways',
          'Spicejet', 'Multiple Carriers',             'Goair',
           'Vistara',          'Air Asia',            'Trujet']
Length: 9, dtype: str

### Date of Journey

In [9]:
print(df['Date_of_Journey'].dtypes)

str

In [10]:
pd.to_datetime(df['Date_of_Journey'], dayfirst=True)

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[us]

### Source

In [11]:
df['Source'].unique()

<StringArray>
['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai']
Length: 5, dtype: str

### Destination

In [12]:
df['Destination'].unique()

<StringArray>
['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad']
Length: 6, dtype: str

### Dep Time

In [13]:
print(df['Dep_Time'].dtype)

str

In [45]:
pd.to_datetime(df['Dep_Time'],format="mixed").dt.time

0        22:20:00
1        05:50:00
2        09:25:00
3        18:05:00
4        16:50:00
           ...
10678    19:55:00
10679    20:45:00
10680    08:20:00
10681    11:30:00
10682    10:55:00
Name: Dep_Time, Length: 10683, dtype: object

### Arrival Time

In [15]:
print(df['Arrival_Time'].dtype)

str

In [47]:
pd.to_datetime(df['Arrival_Time'], format='mixed').dt.time

0        01:10:00
1        13:15:00
2        04:25:00
3        23:30:00
4        21:35:00
           ...
10678    22:25:00
10679    23:20:00
10680    11:20:00
10681    14:10:00
10682    19:15:00
Name: Arrival_Time, Length: 10683, dtype: object

In [16]:
(
    df['Arrival_Time'].str.split(" ", n=1)
    .str.get(1)
    # .count()
    .unique()
)

array(['22 Mar', nan, '10 Jun', '13 Mar', '02 Mar', '10 May', '04 Mar',
       '13 Jun', '28 May', '19 Mar', '07 May', '02 Jun', '16 Jun',
       '19 May', '16 May', '28 Jun', '02 May', '28 Mar', '19 Jun',
       '04 Apr', '25 Mar', '07 Mar', '25 Jun', '07 Jun', '25 May',
       '13 May', '16 Mar', '22 May', '10 Apr', '04 Jun', '20 May',
       '28 Apr', '25 Apr', '10 Mar', '19 Apr', '13 Apr', '02 Apr',
       '23 Mar', '22 Apr', '11 May', '07 Apr', '03 May', '08 Mar',
       '03 Mar', '05 Mar', '22 Jun', '04 May', '26 May', '16 Apr',
       '26 Jun', '29 May', '29 Jun', '29 Mar', '23 May', '17 Jun'],
      dtype=object)

### Duration

In [17]:
print(df['Duration'].dtype)

str

In [18]:
df[df['Duration'].str.split(" ", expand=True)[0].str.contains('h') == False]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
6474,Air India,6/03/2019,Mumbai,Hyderabad,BOM → GOI → PNQ → HYD,16:50,16:55,5m,2 stops,No info,17327

- This observation is wrong. It will be removed.

In [50]:
(
    df['Duration']
    .drop(index=6474)
    .str.split(" ", expand=True)
    .assign(
        hour = lambda df_ : (
            df_[0].str.replace('h', "")
            .astype(int)
            .mul(60)
        ),
        minute = lambda df_ : (
            df_[1].str.replace('m', "")
            .fillna('0')
            .astype(int)
        )
    )[['hour', 'minute']]
    .sum(axis=1)
    .rename('duration_min')
    # .to_frame()
)

0         170
1         445
2        1140
3         325
4         285
         ...
10678     150
10679     155
10680     180
10681     160
10682     500
Name: duration_min, Length: 10682, dtype: int64

### Total Stops

In [20]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [21]:
(
    df['Total_Stops']
    .str.replace('non-stop', '0')
    .fillna('0')
    .str.replace(' stops', "")
    .str.replace(' stop', "")
    .astype(int)
    .unique()
)

array([0, 2, 1, 3, 4])

### Additional Info

In [22]:
df['Additional_Info'].str.title().unique()

<StringArray>
[                     'No Info',  'In-Flight Meal Not Included',
 'No Check-In Baggage Included',              '1 Short Layover',
               '1 Long Layover',              'Change Airports',
               'Business Class',               'Red-Eye Flight',
               '2 Long Layover']
Length: 9, dtype: str

### Price

In [23]:
print(df['Price'].dtype)

int64

In [24]:
df['Price'].describe()

count    10683.000000
mean      9087.064121
std       4611.359167
min       1759.000000
25%       5277.000000
50%       8372.000000
75%      12373.000000
max      79512.000000
Name: Price, dtype: float64

## 4. Data Cleaning

In [66]:
def clean_data(df):

    return (
        df
        .drop(index=6474)
        .drop_duplicates()
        .rename(columns=str.lower)
        .drop(columns='route')
        .assign(
            
            airline = lambda df_ : (
                df_['airline']
                .str.replace(' Premium economy', "")
                .str.replace(' Business', "")
                .str.title()
            ),
            
            date_of_journey = lambda df_ : pd.to_datetime(df_['date_of_journey'], dayfirst=True),

            dep_time = lambda df_ : pd.to_datetime(df_['dep_time'], format='mixed').dt.time,

            arrival_time = lambda df_ : pd.to_datetime(df_['arrival_time'], format='mixed').dt.time,

            duration = lambda temp : (
                temp['duration']
                # .drop(index=6474)
                .str.split(" ", expand=True)
                .assign(
                    hour = lambda df_ : (
                        df_[0].str.replace('h', "")
                        .astype(int)
                        .mul(60)
                    ),
                    minute = lambda df_ : (
                        df_[1].str.replace('m', "")
                        .fillna('0')
                        .astype(int)
                    )
                )[['hour', 'minute']]
                .sum(axis=1)
                # .rename('duration_min')
                # .to_frame()
            ),

            total_stops = lambda df_ :(
                df_['total_stops']
                .str.replace('non-stop', '0')
                .fillna('0')
                .str.replace(' stops', "")
                .str.replace(' stop', "")
                .astype(int)
                # .unique()
            ),

            additional_info = lambda df_ : df_['additional_info'].str.title()
            
        )
    )

In [67]:
clean_data(df)['additional_info'].un

,airline,date_of_journey,source,destination,dep_time,arrival_time,duration,total_stops,additional_info,price
0,Indigo,2019-03-24,Banglore,New Delhi,22:20:00,01:10:00,170,0,No Info,3897
1,Air India,2019-05-01,Kolkata,Banglore,05:50:00,13:15:00,445,2,No Info,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25:00,04:25:00,1140,2,No Info,13882
3,Indigo,2019-05-12,Kolkata,Banglore,18:05:00,23:30:00,325,1,No Info,6218
4,Indigo,2019-03-01,Banglore,New Delhi,16:50:00,21:35:00,285,1,No Info,13302
...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,19:55:00,22:25:00,150,0,No Info,4107
10679,Air India,2019-04-27,Kolkata,Banglore,20:45:00,23:20:00,155,0,No Info,4145
10680,Jet Airways,2019-04-27,Banglore,Delhi,08:20:00,11:20:00,180,0,No Info,7229
10681,Vistara,2019-03-01,Banglore,New Delhi,11:30:00,14:10:00,160,0,No Info,12648
10682,Air India,2019-05-09,Delhi,Cochin,10:55:00,19:15:00,500,2,No Info,11753